package dev.handypage.app.arxiv

/**
 * One arXiv subject category. [group] is the archive code the category belongs
 * to (e.g. "cs" for cs.CL); single-category archives (gr-qc, quant-ph, …)
 * carry themselves as both code and group.
 */
data class ArxivCategory(
    val code: String,
    val label: String,
    val group: String,
)

/**
 * M13: the complete arXiv subject taxonomy (https://arxiv.org/category_taxonomy),
 * official codes and English names, grouped by archive. Android-free so it
 * runs under plain JVM tests.
 */
object ArxivCategories {

    val ALL: List<ArxivCategory> = listOf(
        // Computer Science
        ArxivCategory("cs.AI", "Artificial Intelligence", "cs"),
        ArxivCategory("cs.AR", "Hardware Architecture", "cs"),
        ArxivCategory("cs.CC", "Computational Complexity", "cs"),
        ArxivCategory("cs.CE", "Computational Engineering, Finance, and Science", "cs"),
        ArxivCategory("cs.CG", "Computational Geometry", "cs"),
        ArxivCategory("cs.CL", "Computation and Language", "cs"),
        ArxivCategory("cs.CR", "Cryptography and Security", "cs"),
        ArxivCategory("cs.CV", "Computer Vision and Pattern Recognition", "cs"),
        ArxivCategory("cs.CY", "Computers and Society", "cs"),
        ArxivCategory("cs.DB", "Databases", "cs"),
        ArxivCategory("cs.DC", "Distributed, Parallel, and Cluster Computing", "cs"),
        ArxivCategory("cs.DL", "Digital Libraries", "cs"),
        ArxivCategory("cs.DM", "Discrete Mathematics", "cs"),
        ArxivCategory("cs.DS", "Data Structures and Algorithms", "cs"),
        ArxivCategory("cs.ET", "Emerging Technologies", "cs"),
        ArxivCategory("cs.FL", "Formal Languages and Automata Theory", "cs"),
        ArxivCategory("cs.GL", "General Literature", "cs"),
        ArxivCategory("cs.GR", "Graphics", "cs"),
        ArxivCategory("cs.GT", "Computer Science and Game Theory", "cs"),
        ArxivCategory("cs.HC", "Human-Computer Interaction", "cs"),
        ArxivCategory("cs.IR", "Information Retrieval", "cs"),
        ArxivCategory("cs.IT", "Information Theory", "cs"),
        ArxivCategory("cs.LG", "Machine Learning", "cs"),
        ArxivCategory("cs.LO", "Logic in Computer Science", "cs"),
        ArxivCategory("cs.MA", "Multiagent Systems", "cs"),
        ArxivCategory("cs.MM", "Multimedia", "cs"),
        ArxivCategory("cs.MS", "Mathematical Software", "cs"),
        ArxivCategory("cs.NA", "Numerical Analysis", "cs"),
        ArxivCategory("cs.NE", "Neural and Evolutionary Computing", "cs"),
        ArxivCategory("cs.NI", "Networking and Internet Architecture", "cs"),
        ArxivCategory("cs.OH", "Other Computer Science", "cs"),
        ArxivCategory("cs.OS", "Operating Systems", "cs"),
        ArxivCategory("cs.PF", "Performance", "cs"),
        ArxivCategory("cs.PL", "Programming Languages", "cs"),
        ArxivCategory("cs.RO", "Robotics", "cs"),
        ArxivCategory("cs.SC", "Symbolic Computation", "cs"),
        ArxivCategory("cs.SD", "Sound", "cs"),
        ArxivCategory("cs.SE", "Software Engineering", "cs"),
        ArxivCategory("cs.SI", "Social and Information Networks", "cs"),
        ArxivCategory("cs.SY", "Systems and Control", "cs"),
        // Mathematics
        ArxivCategory("math.AC", "Commutative Algebra", "math"),
        ArxivCategory("math.AG", "Algebraic Geometry", "math"),
        ArxivCategory("math.AP", "Analysis of PDEs", "math"),
        ArxivCategory("math.AT", "Algebraic Topology", "math"),
        ArxivCategory("math.CA", "Classical Analysis and ODEs", "math"),
        ArxivCategory("math.CO", "Combinatorics", "math"),
        ArxivCategory("math.CT", "Category Theory", "math"),
        ArxivCategory("math.CV", "Complex Variables", "math"),
        ArxivCategory("math.DG", "Differential Geometry", "math"),
        ArxivCategory("math.DS", "Dynamical Systems", "math"),
        ArxivCategory("math.FA", "Functional Analysis", "math"),
        ArxivCategory("math.GM", "General Mathematics", "math"),
        ArxivCategory("math.GN", "General Topology", "math"),
        ArxivCategory("math.GR", "Group Theory", "math"),
        ArxivCategory("math.GT", "Geometric Topology", "math"),
        ArxivCategory("math.HO", "History and Overview", "math"),
        ArxivCategory("math.IT", "Information Theory", "math"),
        ArxivCategory("math.KT", "K-Theory and Homology", "math"),
        ArxivCategory("math.LO", "Logic", "math"),
        ArxivCategory("math.MG", "Metric Geometry", "math"),
        ArxivCategory("math.MP", "Mathematical Physics", "math"),
        ArxivCategory("math.NA", "Numerical Analysis", "math"),
        ArxivCategory("math.NT", "Number Theory", "math"),
        ArxivCategory("math.OA", "Operator Algebras", "math"),
        ArxivCategory("math.OC", "Optimization and Control", "math"),
        ArxivCategory("math.PR", "Probability", "math"),
        ArxivCategory("math.QA", "Quantum Algebra", "math"),
        ArxivCategory("math.RA", "Rings and Algebras", "math"),
        ArxivCategory("math.RT", "Representation Theory", "math"),
        ArxivCategory("math.SG", "Symplectic Geometry", "math"),
        ArxivCategory("math.SP", "Spectral Theory", "math"),
        ArxivCategory("math.ST", "Statistics Theory", "math"),
        // Astrophysics
        ArxivCategory("astro-ph.CO", "Cosmology and Nongalactic Astrophysics", "astro-ph"),
        ArxivCategory("astro-ph.EP", "Earth and Planetary Astrophysics", "astro-ph"),
        ArxivCategory("astro-ph.GA", "Astrophysics of Galaxies", "astro-ph"),
        ArxivCategory("astro-ph.HE", "High Energy Astrophysical Phenomena", "astro-ph"),
        ArxivCategory("astro-ph.IM", "Instrumentation and Methods for Astrophysics", "astro-ph"),
        ArxivCategory("astro-ph.SR", "Solar and Stellar Astrophysics", "astro-ph"),
        // Condensed Matter
        ArxivCategory("cond-mat.dis-nn", "Disordered Systems and Neural Networks", "cond-mat"),
        ArxivCategory("cond-mat.mes-hall", "Mesoscale and Nanoscale Physics", "cond-mat"),
        ArxivCategory("cond-mat.mtrl-sci", "Materials Science", "cond-mat"),
        ArxivCategory("cond-mat.other", "Other Condensed Matter", "cond-mat"),
        ArxivCategory("cond-mat.quant-gas", "Quantum Gases", "cond-mat"),
        ArxivCategory("cond-mat.soft", "Soft Condensed Matter", "cond-mat"),
        ArxivCategory("cond-mat.stat-mech", "Statistical Mechanics", "cond-mat"),
        ArxivCategory("cond-mat.str-el", "Strongly Correlated Electrons", "cond-mat"),
        ArxivCategory("cond-mat.supr-con", "Superconductivity", "cond-mat"),
        // Single-category archives
        ArxivCategory("gr-qc", "General Relativity and Quantum Cosmology", "gr-qc"),
        ArxivCategory("hep-ex", "High Energy Physics - Experiment", "hep-ex"),
        ArxivCategory("hep-lat", "High Energy Physics - Lattice", "hep-lat"),
        ArxivCategory("hep-ph", "High Energy Physics - Phenomenology", "hep-ph"),
        ArxivCategory("hep-th", "High Energy Physics - Theory", "hep-th"),
        // Nonlinear Sciences
        ArxivCategory("nlin.AO", "Adaptation and Self-Organizing Systems", "nlin"),
        ArxivCategory("nlin.CD", "Chaotic Dynamics", "nlin"),
        ArxivCategory("nlin.CG", "Cellular Automata and Lattice Gases", "nlin"),
        ArxivCategory("nlin.PS", "Pattern Formation and Solitons", "nlin"),
        ArxivCategory("nlin.SI", "Exactly Solvable and Integrable Systems", "nlin"),
        // Nuclear
        ArxivCategory("nucl-ex", "Nuclear Experiment", "nucl-ex"),
        ArxivCategory("nucl-th", "Nuclear Theory", "nucl-th"),
        // Physics
        ArxivCategory("physics.acc-ph", "Accelerator Physics", "physics"),
        ArxivCategory("physics.ao-ph", "Atmospheric and Oceanic Physics", "physics"),
        ArxivCategory("physics.app-ph", "Applied Physics", "physics"),
        ArxivCategory("physics.atm-clus", "Atomic and Molecular Clusters", "physics"),
        ArxivCategory("physics.atom-ph", "Atomic Physics", "physics"),
        ArxivCategory("physics.bio-ph", "Biological Physics", "physics"),
        ArxivCategory("physics.chem-ph", "Chemical Physics", "physics"),
        ArxivCategory("physics.class-ph", "Classical Physics", "physics"),
        ArxivCategory("physics.comp-ph", "Computational Physics", "physics"),
        ArxivCategory("physics.data-an", "Data Analysis, Statistics and Probability", "physics"),
        ArxivCategory("physics.ed-ph", "Physics Education", "physics"),
        ArxivCategory("physics.flu-dyn", "Fluid Dynamics", "physics"),
        ArxivCategory("physics.gen-ph", "General Physics", "physics"),
        ArxivCategory("physics.geo-ph", "Geophysics", "physics"),
        ArxivCategory("physics.hist-ph", "History and Philosophy of Physics", "physics"),
        ArxivCategory("physics.ins-det", "Instrumentation and Detectors", "physics"),
        ArxivCategory("physics.med-ph", "Medical Physics", "physics"),
        ArxivCategory("physics.optics", "Optics", "physics"),
        ArxivCategory("physics.plasm-ph", "Plasma Physics", "physics"),
        ArxivCategory("physics.pop-ph", "Popular Physics", "physics"),
        ArxivCategory("physics.soc-ph", "Physics and Society", "physics"),
        ArxivCategory("physics.space-ph", "Space Physics", "physics"),
        ArxivCategory("quant-ph", "Quantum Physics", "quant-ph"),
        // Quantitative Biology
        ArxivCategory("q-bio.BM", "Biomolecules", "q-bio"),
        ArxivCategory("q-bio.CB", "Cell Behavior", "q-bio"),
        ArxivCategory("q-bio.GN", "Genomics", "q-bio"),
        ArxivCategory("q-bio.MN", "Molecular Networks", "q-bio"),
        ArxivCategory("q-bio.NC", "Neurons and Cognition", "q-bio"),
        ArxivCategory("q-bio.OT", "Other Quantitative Biology", "q-bio"),
        ArxivCategory("q-bio.PE", "Populations and Evolution", "q-bio"),
        ArxivCategory("q-bio.QM", "Quantitative Methods", "q-bio"),
        ArxivCategory("q-bio.SC", "Subcellular Processes", "q-bio"),
        ArxivCategory("q-bio.TO", "Tissues and Organs", "q-bio"),
        // Quantitative Finance
        ArxivCategory("q-fin.CP", "Computational Finance", "q-fin"),
        ArxivCategory("q-fin.EC", "Economics", "q-fin"),
        ArxivCategory("q-fin.GN", "General Finance", "q-fin"),
        ArxivCategory("q-fin.MF", "Mathematical Finance", "q-fin"),
        ArxivCategory("q-fin.PM", "Portfolio Management", "q-fin"),
        ArxivCategory("q-fin.PR", "Pricing of Securities", "q-fin"),
        ArxivCategory("q-fin.RM", "Risk Management", "q-fin"),
        ArxivCategory("q-fin.ST", "Statistical Finance", "q-fin"),
        ArxivCategory("q-fin.TR", "Trading and Market Microstructure", "q-fin"),
        // Statistics
        ArxivCategory("stat.AP", "Applications", "stat"),
        ArxivCategory("stat.CO", "Computation", "stat"),
        ArxivCategory("stat.ML", "Machine Learning", "stat"),
        ArxivCategory("stat.ME", "Methodology", "stat"),
        ArxivCategory("stat.OT", "Other Statistics", "stat"),
        ArxivCategory("stat.TH", "Statistics Theory", "stat"),
        // Electrical Engineering and Systems Science
        ArxivCategory("eess.AS", "Audio and Speech Processing", "eess"),
        ArxivCategory("eess.IV", "Image and Video Processing", "eess"),
        ArxivCategory("eess.SP", "Signal Processing", "eess"),
        ArxivCategory("eess.SY", "Systems and Control", "eess"),
        // Economics
        ArxivCategory("econ.EM", "Econometrics", "econ"),
        ArxivCategory("econ.GN", "General Economics", "econ"),
        ArxivCategory("econ.TH", "Theoretical Economics", "econ"),
    )

    private val byCodeMap: Map<String, ArxivCategory> = ALL.associateBy { it.code }

    /** Looks up a category by its exact code (e.g. "cs.CL"); null when unknown. */
    fun byCode(code: String): ArxivCategory? = byCodeMap[code]
}
